//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietYeuCauMuon
    {
        public int MaCTYeuCau { get; set; }
        public int MaYeuCau { get; set; }
        public int MaSach { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual YeuCauMuon YeuCauMuon { get; set; }
    }
}
