//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuMuon
    {
        public ChiTietPhieuMuon()
        {
            this.PhieuPhat = new HashSet<PhieuPhat>();
        }
    
        public int MaChiTiet { get; set; }
        public int MaPhieuMuon { get; set; }
        public int MaCuonSach { get; set; }
        public Nullable<System.DateTime> NgayTraThucTe { get; set; }
        public string TinhTrangKhiTra { get; set; }
    
        public virtual CuonSach CuonSach { get; set; }
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual ICollection<PhieuPhat> PhieuPhat { get; set; }
    }
}
