//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuonSach
    {
        public CuonSach()
        {
            this.ChiTietPhieuMuon = new HashSet<ChiTietPhieuMuon>();
        }
    
        public int MaCuonSach { get; set; }
        public int MaSach { get; set; }
        public string TrangThai { get; set; }
        public string ViTriKe { get; set; }
    
        public virtual ICollection<ChiTietPhieuMuon> ChiTietPhieuMuon { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
