//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyThuVienEntities : DbContext
    {
        public QuanLyThuVienEntities()
            : base("name=QuanLyThuVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CuonSach> CuonSach { get; set; }
        public DbSet<ChiTietPhieuMuon> ChiTietPhieuMuon { get; set; }
        public DbSet<ChiTietYeuCauMuon> ChiTietYeuCauMuon { get; set; }
        public DbSet<NguoiDung> NguoiDung { get; set; }
        public DbSet<NhaXuatBan> NhaXuatBan { get; set; }
        public DbSet<PhieuMuon> PhieuMuon { get; set; }
        public DbSet<PhieuPhat> PhieuPhat { get; set; }
        public DbSet<Sach> Sach { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TacGia> TacGia { get; set; }
        public DbSet<TheLoai> TheLoai { get; set; }
        public DbSet<VaiTro> VaiTro { get; set; }
        public DbSet<YeuCauMuon> YeuCauMuon { get; set; }
        public DbSet<V_ThongKeSoLuongSach> V_ThongKeSoLuongSach { get; set; }
    }
}
