//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.PhieuMuon = new HashSet<PhieuMuon>();
            this.PhieuMuon1 = new HashSet<PhieuMuon>();
            this.YeuCauMuon = new HashSet<YeuCauMuon>();
        }
    
        public int MaNguoiDung { get; set; }
        public int MaVaiTro { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public string TrangThaiThe { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual VaiTro VaiTro { get; set; }
        public virtual ICollection<PhieuMuon> PhieuMuon { get; set; }
        public virtual ICollection<PhieuMuon> PhieuMuon1 { get; set; }
        public virtual ICollection<YeuCauMuon> YeuCauMuon { get; set; }
    }
}
