//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuon
    {
        public PhieuMuon()
        {
            this.ChiTietPhieuMuon = new HashSet<ChiTietPhieuMuon>();
        }
    
        public int MaPhieuMuon { get; set; }
        public int MaDocGia { get; set; }
        public Nullable<int> MaThuThu { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public System.DateTime NgayHenTra { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<ChiTietPhieuMuon> ChiTietPhieuMuon { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
