//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuPhat
    {
        public int MaPhieuPhat { get; set; }
        public int MaPhieuMuon { get; set; }
        public decimal SoTienPhat { get; set; }
        public string LyDoPhat { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string TrangThaiThanhToan { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
    }
}
