//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public Sach()
        {
            this.CuonSach = new HashSet<CuonSach>();
            this.ChiTietYeuCauMuon = new HashSet<ChiTietYeuCauMuon>();
        }
    
        public int MaSach { get; set; }
        public string ISBN { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> MaTheLoai { get; set; }
        public Nullable<int> MaTacGia { get; set; }
        public Nullable<int> MaNXB { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        public string AnhBia { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<CuonSach> CuonSach { get; set; }
        public virtual ICollection<ChiTietYeuCauMuon> ChiTietYeuCauMuon { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
