//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ThongKeSoLuongSach
    {
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public string ISBN { get; set; }
        public string TenTheLoai { get; set; }
        public string TenTacGia { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public Nullable<int> SoLuongCoSan { get; set; }
        public Nullable<int> SoLuongDangMuon { get; set; }
        public Nullable<int> SoLuongHong { get; set; }
        public Nullable<int> SoLuongMat { get; set; }
    }
}
