//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauMuon
    {
        public YeuCauMuon()
        {
            this.ChiTietYeuCauMuon = new HashSet<ChiTietYeuCauMuon>();
        }
    
        public int MaYeuCau { get; set; }
        public int MaDocGia { get; set; }
        public Nullable<System.DateTime> NgayYeuCau { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<ChiTietYeuCauMuon> ChiTietYeuCauMuon { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
